name: 🐦 Daily Tweet Bot

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
          pip install typing

      - name: Run Twitter bot
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          export API_KEY="$TWITTER_API_KEY"
          export API_KEY_SECRET="$TWITTER_API_KEY_SECRET"
          export ACCESS_TOKEN="$TWITTER_ACCESS_TOKEN"
          export ACCESS_TOKEN_SECRET="$TWITTER_ACCESS_TOKEN_SECRET"

          python bot_ferias.py
